#version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log
    networks:
      - monitoring-net

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Kafka listens internally and externally
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      # What clients will use to connect (my VMâ€™s IP not localhost)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://193.95.30.190:9092      
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    depends_on:
      - zookeeper
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - monitoring-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      #this one i added to make it work in my local
      - network.host=0.0.0.0
      - xpack.security.enrollment.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - monitoring-net

  #kibana:
   # image: docker.elastic.co/kibana/kibana:7.17.10
    #container_name: kibana
    #ports:
     # - "5601:5601"
    #depends_on:
     # - elasticsearch
    #environment:
     # - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    #networks:
     # - monitoring-net

  airflow-db:
    image: postgres:15
    container_name: airflow-db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow-db-data:/var/lib/postgresql/data
    networks:
      - monitoring-net

  airflow-init:
    image: apache/airflow:2.7.2
    container_name: airflow-init
    depends_on:
      - airflow-db
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
      AIRFLOW__CORE__FERNET_KEY: "ksByHORYtmsjKIM1JhAfA7QGDCFYWRADVh5HNtfizkk="
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    command: >
      bash -c "airflow db init &&
               airflow users create --role Admin --username admin --password admin --firstname admin --lastname admin --email admin@example.com"
    networks:
      - monitoring-net

  airflow-webserver:
    image: apache/airflow:2.7.2

    container_name: airflow-webserver
    restart: always
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      AIRFLOW__CORE__FERNET_KEY: "ksByHORYtmsjKIM1JhAfA7QGDCFYWRADVh5HNtfizkk="
      AIRFLOW__SMTP__SMTP_HOST: smtp.gmail.com
      AIRFLOW__SMTP__SMTP_STARTTLS: True
      AIRFLOW__SMTP__SMTP_SSL: False
      AIRFLOW__SMTP__SMTP_USER: huaweitesttest1@gmail.com
      AIRFLOW__SMTP__SMTP_PASSWORD: ordf ylso cjkm koiq
      AIRFLOW__SMTP__SMTP_PORT: 587
      AIRFLOW__SMTP__SMTP_MAIL_FROM: huaweitesttest1@gmail.com
      _PIP_ADDITIONAL_REQUIREMENTS: apache-airflow-providers-ssh

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./backend:/opt/backend
      - /home/ecs-ai-am/PFE_Project_LatestV/backend:/opt/backend
      - /home/ecs-ai-am/airflow_ssh/id_rsa:/opt/airflow/.ssh/id_rsa:ro


    ports:
      - "8080:8080"
    networks:
      - monitoring-net
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.7.2
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      AIRFLOW__CORE__FERNET_KEY: "ksByHORYtmsjKIM1JhAfA7QGDCFYWRADVh5HNtfizkk="
      _PIP_ADDITIONAL_REQUIREMENTS: apache-airflow-providers-ssh
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./backend:/opt/backend
      - /home/ecs-ai-am/PFE_Project_LatestV/backend:/opt/backend
      - /home/ecs-ai-am/airflow_ssh/id_rsa:/opt/airflow/.ssh/id_rsa:ro


    networks:
      - monitoring-net
    command: scheduler

volumes:
  kafka-data:
  esdata:
  zookeeper-data:
  zookeeper-log:
  airflow-db-data:
networks:
  monitoring-net: